# Generated by Django 2.0.6 on 2018-06-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rilblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
